### ISSUE TITLE
No mean_acc and ci_acc output in summary in evaluation mode

### ISSUE THREAD

**Issue by zhoulinjun1994** [google-research/meta-dataset#38]
I don't find mean_acc and ci_acc in tensorboard while running evaluation mode for 10 datasets.

I think the reason is that:
In train.py Line 261: trainer_instance.evaluate(eval_split) should return 4 parameters: mean_acc, ci_acc, mean_acc_summary, ci_acc_summary related to trainer.py Line 1190.

However, after this line, nothing is written into trainer_instance.summary_writer and it is closed.

I don't know whether the authors intend not to add them to the summary or it's just a missing part. If I'm wrong please correct me.

**Comment by lamblin** [comment]
That is correct, these values (which are recorded for the validation split during training) are not recorded in the summaries during evaluation, just printed in the log (stdout by default I think).

Adding them to the summaries, so that tensorboard can find them, would be an improvement. Feel free to send a PR :)

Note that everything needed to recompute those values is still written in the summaries (even though TensorBoard does not display them), as all the prediction and targets of the test episodes are there. You can take inspiration from `meta_dataset/analyze.py` to read these values, and recompute the mean and 95% CI of the accuracy.
