### ISSUE TITLE
Some confusion about the collapse() function in the /imagenet_specification.py

### ISSUE THREAD

**Issue by Hanzy1996** [google-research/meta-dataset#45]
https://github.com/google-research/meta-dataset/blob/ece21839d9b3b31dc0e5addd2730605df5dbb991/meta_dataset/data/imagenet_specification.py#L307
According to the note, you have removed all nodes with only one child and attach that child to their parents and I understand how to achieve this. But it's still confusing for me that why this operation is needed?

**Comment by lamblin** [comment]
I think there are two goals:
- to have no internal node is the parent of a single leaf, so they can be (in principle) the root of an episode's classes. We have since added eligibility requirements in the sampling procedure, so this might not be necessary any more.
- to avoid over-representing the classes from that branch, as selecting one node or its only child would result in sampling the same episode class set.

**Comment by Hanzy1996** [comment]
It's very kind of you to make such a detailed explanation. Thank you for your patience. Your explanations about the sampling and ImageNet are quite clear. I have understood the codes of sampling and ImageNet better.

Much appreciation again!

**Comment by lamblin** [comment]
No problem, don't hesitate to ask other questions if some things are not clear enough!
